---
- name: Create user
  user:
    name: prometheus
    state: present
    create_home: no
    shell: /bin/bash

- name: Make directory
  file:
    path: /opt/blackbox_exporter
    state: directory
    owner: prometheus
    group: prometheus

- name: Make download directory
  file:
    path: /opt/blackbox_exporter/downloads
    state: directory
    owner: prometheus
    group: prometheus

- name: Make executables directory
  file:
    path: /opt/blackbox_exporter/releases
    state: directory
    owner: prometheus
    group: prometheus

- name: Download blackbox_exporter
  get_url:
    url: https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz
    dest: /opt/blackbox_exporter/downloads/{{ blackbox_exporter_version }}.tar.gz
    owner: prometheus
    group: prometheus

- name: Unpack tarball
  unarchive:
    src: /opt/blackbox_exporter/downloads/{{ blackbox_exporter_version }}.tar.gz
    remote_src: yes
    dest: /opt/blackbox_exporter/releases/
    creates: /opt/blackbox_exporter/releases/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter
    owner: prometheus
    group: prometheus

- name: Create blackbox config
  template:
    src: blackbox.yml.j2
    dest: /opt/blackbox_exporter/blackbox.yml
    owner: prometheus
    group: prometheus
  notify:
    - "restart blackbox_exporter"

- name: Create systemd config
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
  notify:
    - "reload systemd"
    - "restart blackbox_exporter"

- name: "Flush handlers"
  meta: flush_handlers

- name: enable blackbox_exporter and ensure running
  service:
    name: blackbox_exporter
    state: started
    enabled: yes
